# POST http://localhost:3001/create-blog/get-blog
# Content-Type: application/json

# {
#     "blog_id": "Blog-ggtFn9aArjdb9drM3hJJJ2g"
# }

# POST http://localhost:3001/signin
# Content-Type: application/json

# {
#     "email": "piyarat4543@gmail.com",
#     "password": "Jungkook1997*"
# }

POST http://localhost:3001/create-blog/user-written-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDdiODVmMTE0NGI5NDlkNmFmNjg3NyIsImlhdCI6MTcyOTU2NjA2OH0.ng30QedxGKnh1FxHj8jesh3Q7OcKMFfS0MgbYFVTGEI

{
    "page": 1,
    "draft": false
}

