# POST http://localhost:3001/create-blog/get-blog
# Content-Type: application/json

# {
#     "blog_id": "Blog-ggtFn9aArjdb9drM3hJJJ2g"
# }

# POST http://localhost:3001/signin
# Content-Type: application/json

# {
#     "email": "Piyarat4543@gmail.com",
#     "password": "Jungkook1997"
# }

POST http://localhost:3001/notifications/new-notification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDdiODVmMTE0NGI5NDlkNmFmNjg3NyIsImlhdCI6MTcyOTM2MzE4NX0.dL8JFVPV4mcfsCbQ_su77Hv0OrOYrIYNCE-Rhps76ec
